---
LLMProviders:
  - name: bam
    url: "https://bam-api.res.ibm.com"
    credentials_path: bam_api_key.txt
    models:
      - name: ibm/granite-13b-chat-v2
  - name: openai
    url: "https://api.openai.com/v1"
    credentials_path: openai_api_key.txt
    models:
      - name: gpt-4-1106-preview
OLSConfig:
  enable_debug_ui: false
  conversation_cache:
    type: memory
    memory:
      max_entries: 1000
  logging_config:
    app_log_level: info
    library_log_level: warning
  default_provider: bam
  default_model: ibm/granite-13b-chat-v2
