llm_providers:
  - name: bam
    url: "https://bam-api.res.ibm.com"
    credentials_path: bam_api_key.txt
    models:
      - name: ibm/granite-13b-chat-v2
  - name: openai
    url: "https://api.openai.com/v1"
    credentials_path: openai_api_key.txt
    models:
      - name: gpt-4-1106-preview
      - name: gpt-3.5-turbo
ols_config:
  reference_content:
#    product_docs_index_path: "./vector-db/ocp-product-docs"
#    product_docs_index_id: product
  conversation_cache:
    type: memory
    memory:
      max_entries: 1000
  logging_config:
    app_log_level: info
    lib_log_level: warning
  default_provider: bam
  default_model: ibm/granite-13b-chat-v2
# question_filters:
# - name: ip_filter
#   regular_expression: '(?:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
#   replace_with_string: "redacted_ip"
# - name: url_filter
#   regular_expression: '(?:https?://)?(?:www\.)?[\w\.-]+\.\w+'
#   replace_with_string: "redacted_url"
dev_config:
  enable_dev_ui: true
  # llm_temperature_override: 0
  # disable_question_validation: false
  # disable_auth: false
